# Copyright (c) 2021, the Dart project authors.  Please see the AUTHORS file
# for details. All rights reserved. Use of this source code is governed by a
# BSD-style license that can be found in the LICENSE file.

name: cronet
version: 0.0.4+2
homepage: https://github.com/google/cronet.dart
description: Experimental Cronet dart bindings.

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  ffi: ^1.1.2
  path: ^1.8.0
  args: ^2.1.1
  cli_util: ^0.3.3
  archive: ^3.1.2

dev_dependencies:
  ffigen: ^2.4.2
  lints: ^1.0.1
  test: ^1.16.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: dev.google.cronet
        pluginClass: CronetPlugin
      linux:
        pluginClass: CronetPlugin
      windows:
        pluginClass: CronetPlugin
